### ISSUE TITLE
only call firebase once

### ISSUE THREAD

**Issue by mwcz** [redhataccess/portal-platformers#12]
Modify the game to only call the firebase API on the initial boot.  Currently, the API is called every time the select state is entered.  Tyler found the following race condition:

 1. start the game, choose a character
 2. click reset
 3. choose another character (the faster the better; clicking quickly has a higher chance to trigger the bug)

**Expected outcome**: join the game as the character chosen in step 3.

**Actual outcome**: entering the select state as a result of step 2 causes the firebase API to be called again, so even though the players show up on screen, the select state's `this.player` and `this.players` are undefined and empty arrays, respectively, because the second API call hasn't returned yet.

**Comment by kylebuch8** [comment]
Can you add just a _bit_ more detail here?

**Comment by mwcz** [comment]
Sure, I was going to tackle this myself, but I'll fill in the top post with a description in case someone else wants to grab it.

**Comment by kylebuch8** [comment]
I don't think we need this anymore since we the reset button now does `location.reload()`
